[project]
name = "language-of-tenses"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "dask-jobqueue>=0.9.0",
    "dask[distributed]>=2025.3.0",
    "requests>=2.32.3",
    "tqdm>=4.67.1",
]
