name: Test

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v5
      with:
        python-version: '3.10'
    - name: Install uv
      uses: astral-sh/setup-uv@v6
      with:
        python-version: '3.10'
    - name: Install dependencies
      run: |
        uv sync
        uv add pytest
    - name: Run tests
      run: |
        uv run pytest -q
